# ref: https://mise.jdx.dev/tasks/
#:schema https://mise.jdx.dev/schema/mise-task.json

[commit]
depends = "buni"
run = [
	"{% if flag(name='staged') == 'false' %}git add .{% endif %}",
	"bun run git-cz",
]
raw = true

[execute]
depends = "buni --production"
run = "bun run src/index.ts"

[check]
depends = "check:*"

["check:tsc"]
depends = "buni"
run = "bun run tsc {% if env.CI is defined %}--incremental false{% endif %}"

["check:biome"]
run = "biome {% if env.LINT is undefined %}check --write{% else %}ci{% endif %} --error-on-warnings"

["check:actionlint"]
run = "actionlint -color"
# SC2312: check-extra-masked-returns
# pipefail is set by shell: bash in GitHub Actions but cannot be detected by shellcheck
# ref: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#defaultsrunshell
env = { "SHELLCHECK_OPTS" = "--enable=all --exclude=SC2312" }

["check:ghalint"]
wait_for = "check:pinact"
run = "ghalint run"

["check:pinact"]
run = "pinact run --verify {% if env.LINT is defined %}--check{% endif %}"

["check:taplo"]
run = [
	"taplo lint",
	"taplo fmt {% if env.LINT is defined %}--check --diff{% endif %}",
]

["check:yamlfmt"]
run = "yamlfmt {% if env.LINT is defined %}-lint{% endif %} ."

["check:yamllint"]
run = "yamllint --strict ."

["check:typos"]
run = "typos {% if env.LINT is undefined %}--write-changes{% endif %}"

["check:jsonschema"]
run = "jschema-validator"

["check:ignore-sync"]
run = "ignore-sync ."
depends_post = "{% if env.CI is defined %}util:nodiff{% else %}util:donothing{% endif %}"

["buni"]
run = "bun install --frozen-lockfile"

["util:nodiff"]
run = ["git add .", "git diff --staged --exit-code"]
hide = true

["util:donothing"]
run = ""
hide = true
